export const cardInfos = [
  {
    name: "气温",
    value: "21.0",
    unit: "(℃)",
    tip: "通道1",
    imgUrl: require("../../../assets/img/weather-station/fengsu.png"),
    color: "#f5b762",
  },
  {
    name: "气湿",
    value: "22.4",
    unit: "(%RH)",
    tip: "通道2",
    imgUrl: require("../../../assets/img/weather-station/shuidi.png"),
    color: "#3eb983",
  },
  {
    name: "气压",
    value: "875.0",
    unit: "(hpa)",
    tip: "通道3",
    imgUrl: require("../../../assets/img/weather-station/sun.png"),
    color: "#4cb8e9",
  },
  {
    name: "光照",
    value: "0.6",
    unit: "(lux)",
    tip: "通道4",
    imgUrl: require("../../../assets/img/weather-station/ph.png"),
    color: "#4cb8e9",
  },
  {
    name: "风速",
    value: "0.0",
    unit: "(m/s)",
    tip: "通道5",
    imgUrl: require("../../../assets/img/weather-station/huashu.png"),
    color: "#4978c0",
  },
  {
    name: "风向",
    value: "180.0",
    unit: "",
    tip: "通道6",
    imgUrl: require("../../../assets/img/weather-station/wenduji.png"),
    color: "#f5b762",
  },
  {
    name: "雨量",
    value: "0.0",
    unit: "(mm)",
    tip: "通道7",
    imgUrl: require("../../../assets/img/weather-station/fengxiang.png"),
    color: "#f5b762",
  },
  {
    name: "土温",
    value: "24.3",
    unit: "(℃)",
    tip: "通道8",
    imgUrl: require("../../../assets/img/weather-station/shidu.png"),
    color: "#4978c0",
  },
  {
    name: "土湿",
    value: "21.8",
    unit: "(%RH)",
    tip: "通道9",
    imgUrl: require("../../../assets/img/weather-station/wenduji.png"),
    color: "#4978c0",
  },
  {
    name: "PH",
    value: "7.9",
    unit: "(ph)",
    tip: "通道10",
    imgUrl: require("../../../assets/img/weather-station/shidu.png"),
    color: "#3eb983",
  },
  {
    name: "氮",
    value: "6.0",
    unit: "(mg/kg)",
    tip: "通道11",
    imgUrl: require("../../../assets/img/weather-station/wenduji.png"),
    color: "#4978c0",
  },
  {
    name: "磷",
    value: "9.0",
    unit: "(mg/kg)",
    tip: "通道12",
    imgUrl: require("../../../assets/img/weather-station/shidu.png"),
    color: "#3eb983",
  },
  {
    name: "钾",
    value: "21.0",
    unit: "(mg/kg)",
    tip: "通道9",
    imgUrl: require("../../../assets/img/weather-station/wenduji.png"),
    color: "#4978c0",
  }
];
